

# Variables and root user used
variables:
  MYSQL_PASSWORD: 2BtrCM9agZho1wMc9xT1
  MYSQL_DATABASE: db


before_script:
    - echo "Samuel L jackson";
    - ./composer.phar install 
    - pwd
job:
  script: echo 'my first job'



  
