<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2aylM6B\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2aylM6B/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2aylM6B.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2aylM6B\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container2aylM6B\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '2aylM6B',
    'container.build_id' => 'cf4917d4',
    'container.build_time' => 1580832765,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2aylM6B');
